##### experiment wide
iterations: 1
seed: 13

##### data specific
dataset_name: 'enth'
dataset: 'data/enth/ENTH_env_20.csv'
target_column: 'thermal_cozie'
target_values:
    - 9.0
    - 10.0
    - 11.0
categorical_features:
    - 'clothing'
model: 'rdf'
scorer: 'f1_micro'
use_val: False
